---
- hosts: www
  become: yes
  gather_facts: true

  roles:
    - role: creidinger.common
    - role: creidinger.php
    - role: geerlingguy.composer
    - role: creidinger.apache
    - role: creidinger.mysql_server
    - role: creidinger.phpmyadmin
      when: install_phpymyadmin is defined
    - role: laravel_config
    - role: deploy
      when: deploy_src_files

  tasks:
  - name: restart apache
    service:
      name: apache2
      state: restarted
      enabled: yes

  post_tasks:
    - name: open URL
      become: no
      local_action: shell open "{{ base_url }}"
      ignore_errors: yes
