---
- hosts: www
  become: yes
  gather_facts: true

  roles:
    - role: creidinger.common
    - role: creidinger.php
    - role: creidinger.apache
    - role: creidinger.mysql_server
    - role: creidinger.phpmyadmin
      when: install_phpymyadmin is defined

  tasks:
  # - name: Install npm packages based on /assets/pacage.json
  #   npm:
  #     path: /vagrant/src/public_html/assets
  #
  # - name: Update composer packages
  #   composer:
  #     command: updated
  #     working_dir: /vagrant/src/public_html
  #
  - name: restart apache
    service:
      name: apache2
      state: restarted
      enabled: yes

  post_tasks:
    - name: open URL
      become: no
      local_action: shell open "{{ base_url }}"
      ignore_errors: yes
